---

- name: Apache
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  # - name: Enable repo
  #   yum:
  #     enablerepo: "epel"
  #
  # - name: httpd install
  #   yum:
  #     name: httpd
  #     state: present
  #
  # - name: Unconditionally reboot the machine with all defaults
  #   reboot:
  #
  # - name: Disable service httpd
  #   ansible.builtin.systemd:
  #     name: httpd
  #     enabled: no
  #
  # - name: reboot 20
  #   reboot:
  #     pre_reboot_delay: 20
  #
  # - name: Populate service facts
  #   service_facts:
  #
  # - name: Print service facts
  #   debug:
  #     var: ansible_facts.services['httpd.service'].state
  #     verbosity: 2
  #
  # - name: Enable service httpd
  #   ansible.builtin.systemd:
  #     name: httpd
  #     enabled: yes
  #     daemon_reload: yes
  #
  # - name: stop service httpd on centos
  #   ansible.builtin.systemd:
  #     state: stopped
  #     name: httpd
  #
  # - name: start service httpd on centos
  #   ansible.builtin.systemd:
  #     state: started
  #     name: httpd
  #
  # - name: Unconditionally reboot the machine with all defaults
  #   reboot:

  - name: Find all
    find:
      paths:
        - /etc/httpd/conf
        - /etc/httpd/conf.d

      # - name: Gather the package facts
  #   package_facts:
  #     manager: auto

  # - name: Print the package facts
  #   ansible.builtin.debug:
  #     var: ansible_facts.packages
  #     verbosity: 2
