---

- name: Test gather_facts
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Populate service facts
    service_facts:

  - name: Print service facts
    debug:
      var: ansible_facts.services
      verbosity: 2
