---

- name: Test gather_facts
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Gather the package facts
    package_facts:
      manager: auto

  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages
      verbosity: 2
