---
- name: ping
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{test_user[0]}}"

#Добавление пользователей
  - name: Add the user 'Keni' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{test_user[1]}}"


  - name: Add the user 'Tom' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{test_user[2]}}"

#Создание папки для копирования файла в корень
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /mydir
      state: directory
      mode: '0777'
#Копируем в папку наш файл
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: '../../files/test.txt'
      dest: '/mydir/{{test_user[0]}}_01.txt'
      owner: "{{test_user[0]}}"
      group: "{{test_user[0]}}"

#Меняем хостнейм
  - name: Set a hostname specifying strategy
    ansible.builtin.hostname:
      name: s-test-01

#Убираем апач из автозагрузки
  - name: disable service httpd
    ansible.builtin.systemd:
      name: httpd
      enabled: no
      daemon_reload: yes
#Резервная копия конфига
  - name: Copy
    ansible.builtin.copy:
      src: /etc/ssh/sshd_config
      dest: /root/ssh_test_config
      remote_src: yes

#Создание папки для отчета локально
  - name: create directory
    file:
      path: /ansible/audit/linux_severs #?Тут опечатка в задании или так надо
      state: directory
      mode: 0777
    delegate_to: localhost

#Забираем отчет по ssh
  - name: ansible copy к себе
    fetch:
      src: /etc/ssh/sshd_config
      dest: /ansible/audit/linux_severs/sshd_config
      flat: yes
#Если нет строки PermitRootLogin yes добавить
  - lineinfile:
      path: /etc/ssh/sshd_config
      #regexp: '^PermitRootLogin yes'
      # insertafter: '^#PermitRootLogin'
      line: 'PermitRootLogin yes'

#Найти строку и закоментировать PermitRootLogin yes
  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin yes'
      # insertafter: '^#PermitRootLogin'
      line: '#PermitRootLogin yes'
