---

# - name: set fact
#   set_fact:
#     server_id: '47dab8b8-f58f-44ed-8c2b-9309f4b9bf39'

- name: SERVER
  uri:
    url: 'https://api.clo.ru//v1/servers/{{ server_id }}/start'
    status_code: 202
    method: POST
    headers:
      Content-Type: 'application/json'
      Authorization: 'Bearer {{ token }}'

  register: rez3

- name: Debug3
  debug:
    var: rez3
