---
- name: Install
  hosts: all
  #become: yes
  gather_facts: yes
  tasks:
  - name: Install
    apt:
      name: '{{ item }}'
    with_items:
      - python3-pip
      - virtualenv



  - name: Update pip
    shell:  'pip3 install pip -U'

  - name: pip
    pip:
      name:
        - aiohttp
        - aiohttp_jinja2
        - jinja2
      virtualenv: /opt/app/venv
      virtualenv_python: python3

  - name: Git checkout
    git:
      repo: https://github.com/RoboInterativo/back-front-example
      dest: /opt/back-front-example

#    remote_src: yes
#  roles:
#    - name: Install consul agents
#      role: nodejs

  # tasks:
  # - name: nginx-docker
  #   debug:
  #     msg: 'Hello'  # - name: Get OS type
  #   debug:
  #     var: ansible_facts.distribution
  # - name: Update repositories cache and install  package
  #   apt:
  #     name: '{{ item }}'
  #     update_cache: yes
  #   with_items: '{{ package_list }}'
  #
  # - name: Create Dir
  #   file:
  #     path: '~/ansible'
  #     state: directory


#    when: ansible_facts.distribution=='Ubuntu'
  # - name: Print all available facts
  #   ansible.builtin.debug:

  #     var: ansible_facts
