---
- name: Install
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: ping
    ping:

  - name: hello
    debug:
      msg: 'Hello'

  - name: apt
    apt:
      name: 'nginx'
  # - name: Get OS type
  #   debug:
  #     var: ansible_facts.distribution
  # - name: Update repositories cache and install  package
  #   apt:
  #     name: '{{ item }}'
  #     update_cache: yes
  #   with_items: '{{ package_list }}'
  #
  # - name: Create Dir
  #   file:
  #     path: '~/ansible'
  #     state: directory


#    when: ansible_facts.distribution=='Ubuntu'
  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts
