---
- name: Test ping host all
  hosts: robo
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: nginx
      state: absent
